contributing/code-of-conduct.md
This is copied from Contributor Covenant
http://contributor-covenant.org/
=> Add a code of conduct

contributing/developers.md
OMG look we have a full developer guide! 🎉🍺🍰🍸
At least I _think_ it's complete, for now. @hollsk, @joseluisbolos: fancy reviewing?
=> Finish off the developer guide

contributing/developers.md
=> non-literal text

contributing/communications.md
Input requested :-)
I've tried to keep it concise, but there may be things missed out. Perhaps there are specific guidelines for _technical_ writing I don't know of? @typothecary ?
=> first attempt at writing style overhaul

pages/home.md
Addresses https://github.com/pa11y/org/issues/4
=> Rename all the repos and uppercase Pa11y

_includes/header.html, contributing/companies.md
resolves #24 
Have I missed or misrepresented anything?
=> add company contribution guide

contributing/developers.md
=> add the comment style we expect

contributing/communications.md, contributing/developers.md, pages/home.md
=> Fix typos/grammar

README.md, _includes/header.html, contributing/code-of-conduct.md, contributing/communications.md, contributing/companies.md, contributing/designers.md, contributing/developers.md, contributing/index.md, pages/404.md, pages/contact.md, pages/home.md, pages/projects.md
Think I got them all.
Needs double checking. Especially scenarios where there are names that need capitalising.
=> sentence case titles #40

contributing/communications.md, contributing/index.md
I think we can probably close #14 after this. We're actually pretty OK with following our plain english guide now, and we can fix issues as we find them 👍
=> Make minor copy tweaks for clarity

_includes/header.html, _layouts/page.html, asset/image/svg/arrow-down-white.svg, asset/image/svg/arrow-down-yellow.svg, asset/image/svg/arrow-down.svg, asset/script/site.js, asset/style/_header.scss, asset/style/site.scss
This work adds a header menu to the pa11y site. There is a single submenu that is controlled with javascript. I experimented with adding keyboard navigation to the sub-menu but decided it was overkill since all the sub-menu links are available on the next page.
=> adds a header-menu with a single drop down

_includes/header.html, _layouts/page.html, asset/style/site.scss
This isn't ready to be merged yet, just doing the work so that all we need to do is click "merge" when we're ready to launch the new site.
Resolves #33.
=> Remove the "under construction" notice

_data/team.yml
I changed my github username, just updating here. Resisted the urge to move myself to the top of the list!
=> Update github username from howlingmad to alexkilgour

contributing/index.md
We accidentally lost this when we removed the submenu!
=> Add body copy link to companies guide

pages/home.md
=> Add Koa11y to the homepage

pages/home.md
Adds Mee's new post to the resources section. 
Should I put "pa11y" in the link text, do you think? I've followed the same pattern as the other titles but this is the only one where pa11y isn't in the title of the post!
=> add travis CI cruft post

_includes/flash.html, _layouts/page.html, asset/style/site.scss
Adds a new flash message. Hard coded text for now /shrug 
it looks like this:
=> add flash message with link to survey

pages/home.md
* Changed title of the cruft.io post to distinguish it from Ire's new one
* Put Ire's post right at the top and moved the cruft one and my actions posts to the bottom - Ire's covers both, and pa11y core is our most popular repo
* Put the two dashboard posts 2nd+3rd as that's our 2nd most popular repo
* Sorry about your CI post Mee 😁
=> reorder links and add bitsofcode post

_includes/flash.html, _layouts/page.html
doesn't remove the template itself, in case we ever want to use it again
you never know!
=> remove the flash message and uninclude the template

README.md, _layouts/post.html, _posts/2017-09-14-updating-html-codesniffer.md
More details are in the README changes.
=> Add authorship to news items

README.md
I'll create another PR reverting this change, to be merged in around two weeks from 12th August.
=> Add our design survey to the README

README.md
Reverts pa11y/pa11y.github.io#89 - to be merged once the survey is closed.
=> Revert "Add our design survey to the README"

_data/tutorials.yml
As suggested in https://github.com/pa11y/pa11y-ci/issues/130
=> Add new pa11y-ci tutorial to list

_data/tutorials.yml
I _think_ this is the right syntax 🤷
=> Add meaningful heading names to tutorials page

_data/tutorials.yml, pages/tutorials.md
=> Headings: make headings more descriptive headings.

_includes/footer.html
Image element has explicit width and height. Reduce layout shifts and improve CLS
=> Add Creative Commons image dimensions to markup to improve CLS

_data/team.yml, _includes/footer.html, _includes/team-list.html, contributing/communications.md, contributing/companies.md, contributing/developers.md, pages/contact.md, pages/news.md
Actually part of #114, I just forgot to save this one file before staging, committing, pushing, and merging the other changes 🙄
=> remove **all** references to Twitter
